name: Sample Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    inputs:
      param1:
        description: 'Parameter 1 description'
        required: true
      param2:
        description: 'Parameter 2 description'
        required: true
      param3:
        description: 'Parameter 3 description'
        required: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Parameters
        run: |
          echo "Parameter 1: ${{ inputs.param1 }}"
          echo "Parameter 2: ${{ inputs.param2 }}"
          echo "Parameter 3: ${{ inputs.param3 }}"

      # Add your workflow steps here
