name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      flm_version:
        description: 'FLM Version'
        required: true
      kube_version:
        description: 'Kubernetes Version'
        required: true
      name:
        description: 'Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Parameters
        run: |
          echo "FLM Version: ${{ github.event.inputs.flm_version }}"
          echo "Kubernetes Version: ${{ github.event.inputs.kube_version }}"
          echo "Name: ${{ github.event.inputs.name }}"

      # Add your workflow steps here
